# Generated by Django 4.1.1 on 2022-10-21 09:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Worked_date', models.DateField(default=datetime.date(2022, 10, 21), verbose_name='勤務日')),
                ('Worktime', models.IntegerField(verbose_name='勤務時間')),
                ('wage', models.IntegerField(blank=True, default=1000, null=True, unique=True, verbose_name='時給')),
            ],
        ),
        migrations.CreateModel(
            name='Yearwage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(default=1000000, unique=True, verbose_name='年収')),
            ],
        ),
    ]
