# Generated by Django 4.1.1 on 2022-11-20 03:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='Worked_date',
            field=models.DateField(default=datetime.date(2022, 11, 20), unique=True, verbose_name='勤務日'),
        ),
    ]
