# Generated by Django 4.1.1 on 2022-10-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='wage',
            field=models.IntegerField(default=1000, verbose_name='時給'),
        ),
    ]
