# Generated by Django 4.1.1 on 2023-01-07 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='yukyu',
            field=models.BooleanField(verbose_name='有給'),
        ),
    ]
