# Generated by Django 4.1.1 on 2022-10-27 08:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0002_alter_work_wage'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='total_wage',
            field=models.IntegerField(default=1, verbose_name='日給'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='work',
            name='Worked_date',
            field=models.DateField(default=datetime.date(2022, 10, 27), verbose_name='勤務日'),
        ),
        migrations.AlterField(
            model_name='work',
            name='wage',
            field=models.IntegerField(verbose_name='時給'),
        ),
    ]
