# Generated by Django 4.1.1 on 2022-11-20 04:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0002_alter_work_worked_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wage',
            name='name',
            field=models.PositiveIntegerField(verbose_name='時給'),
        ),
        migrations.AlterField(
            model_name='work',
            name='Worked_date',
            field=models.DateField(default=datetime.date(2022, 11, 20), verbose_name='勤務日'),
        ),
        migrations.AlterField(
            model_name='yearwage',
            name='name',
            field=models.PositiveIntegerField(default=1000000, verbose_name='年収'),
        ),
    ]
