# Generated by Django 4.1.1 on 2023-01-07 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0002_alter_work_yukyu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='Worktime_h',
            field=models.PositiveIntegerField(verbose_name='勤務時間 (時間)'),
        ),
        migrations.AlterField(
            model_name='work',
            name='Worktime_h_2',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='途中で時給が変わる場合の勤務時間 (時間) ※空欄可'),
        ),
        migrations.AlterField(
            model_name='work',
            name='Worktime_m',
            field=models.PositiveIntegerField(default=0, verbose_name='勤務時間 (分)'),
        ),
        migrations.AlterField(
            model_name='work',
            name='Worktime_m_2',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='途中で時給が変わる場合の勤務時間 (分) ※空欄可'),
        ),
        migrations.AlterField(
            model_name='work',
            name='wage_2',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='途中で時給が変わる場合の時給 ※空欄可'),
        ),
        migrations.AlterField(
            model_name='work',
            name='zangyo_h',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='残業時間（時間）※空欄可'),
        ),
        migrations.AlterField(
            model_name='work',
            name='zangyo_m',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='残業時間（分）※空欄可'),
        ),
    ]
