# Generated by Django 4.1.1 on 2022-10-27 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0003_work_total_wage_alter_work_worked_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='total_wage',
            field=models.IntegerField(editable=False, verbose_name='日給'),
        ),
    ]
