# Generated by Django 4.1.1 on 2022-11-20 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0003_alter_wage_name_alter_work_worked_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='total_yukyu',
            options={'verbose_name': '有給'},
        ),
        migrations.AlterModelOptions(
            name='wage',
            options={'verbose_name': '時給'},
        ),
        migrations.AlterModelOptions(
            name='yearwage',
            options={'verbose_name': '年収'},
        ),
        migrations.AlterModelOptions(
            name='zangyo',
            options={'verbose_name': '残業手当'},
        ),
        migrations.AddField(
            model_name='total_yukyu',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ログインユーザー'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wage',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ログインユーザー'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='work',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ログインユーザー'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yearwage',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ログインユーザー'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zangyo',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ログインユーザー'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='total_yukyu',
            name='name',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='wage',
            name='name',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='yearwage',
            name='name',
            field=models.PositiveIntegerField(default=1000000),
        ),
        migrations.AlterField(
            model_name='zangyo',
            name='name',
            field=models.PositiveIntegerField(),
        ),
    ]
