# Generated by Django 4.1.1 on 2023-02-02 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0003_alter_work_worktime_h_alter_work_worktime_h_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='total_worktime_h',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='一日の勤務時間(時間)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='work',
            name='total_worktime_m',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='一日の勤務時間(分)'),
            preserve_default=False,
        ),
    ]
