# Generated by Django 4.1.1 on 2022-10-31 01:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0004_alter_work_total_wage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='work',
            name='Worked_date',
            field=models.DateField(default=datetime.date(2022, 10, 31), verbose_name='勤務日'),
        ),
    ]
