# Generated by Django 4.1.1 on 2023-02-02 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0004_work_total_worktime_h_work_total_worktime_m'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='zangyo_wage',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='残業時給'),
            preserve_default=False,
        ),
    ]
