# Generated by Django 4.1.1 on 2022-11-01 23:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0005_wage_alter_work_worked_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yukyu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(verbose_name='有給')),
            ],
        ),
        migrations.AddField(
            model_name='work',
            name='yukyu',
            field=models.IntegerField(default=0, verbose_name='有給'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='work',
            name='Worked_date',
            field=models.DateField(default=datetime.date(2022, 11, 2), verbose_name='勤務日'),
        ),
    ]
