# Generated by Django 4.1.1 on 2022-11-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0005_total_yukyu_number_wage_number_yearwage_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wage',
            name='number',
        ),
        migrations.AlterField(
            model_name='total_yukyu',
            name='number',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='yearwage',
            name='number',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='zangyo',
            name='number',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
