# Generated by Django 4.1.1 on 2022-11-01 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0006_yukyu_work_yukyu_alter_work_worked_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Yukyu',
            new_name='total_yukyu',
        ),
    ]
