# Generated by Django 4.1.1 on 2022-11-21 12:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0006_remove_wage_number_alter_total_yukyu_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='total_yukyu',
            name='name',
            field=models.PositiveIntegerField(verbose_name='有給'),
        ),
        migrations.AlterField(
            model_name='total_yukyu',
            name='number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='wage',
            name='name',
            field=models.PositiveIntegerField(verbose_name='時給'),
        ),
        migrations.AlterField(
            model_name='work',
            name='Worked_date',
            field=models.DateField(default=datetime.date(2022, 11, 21), verbose_name='勤務日'),
        ),
        migrations.AlterField(
            model_name='yearwage',
            name='name',
            field=models.PositiveIntegerField(default=1000000, verbose_name='年収'),
        ),
        migrations.AlterField(
            model_name='yearwage',
            name='number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='zangyo',
            name='name',
            field=models.PositiveIntegerField(verbose_name='残業手当'),
        ),
        migrations.AlterField(
            model_name='zangyo',
            name='number',
            field=models.PositiveIntegerField(),
        ),
    ]
