# Generated by Django 4.1.1 on 2022-11-02 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0007_rename_yukyu_total_yukyu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='Worktime',
        ),
        migrations.AddField(
            model_name='work',
            name='Worktime_h',
            field=models.IntegerField(default=4, verbose_name='勤務時間-時間'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='work',
            name='Worktime_m',
            field=models.IntegerField(default=10, verbose_name='勤務時間-分'),
            preserve_default=False,
        ),
    ]
