# Generated by Django 4.1.1 on 2022-11-23 11:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0008_alter_total_yukyu_number_alter_yearwage_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wage',
            name='name',
            field=models.PositiveIntegerField(default=1000, verbose_name='時給'),
        ),
        migrations.AlterField(
            model_name='work',
            name='Worked_date',
            field=models.DateField(default=datetime.date(2022, 11, 23), verbose_name='勤務日'),
        ),
        migrations.AlterField(
            model_name='yearwage',
            name='number',
            field=models.PositiveIntegerField(default=1, unique=True),
        ),
    ]
