# Generated by Django 4.1.1 on 2022-11-03 00:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0008_remove_work_worktime_work_worktime_h_work_worktime_m'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wage',
            name='name',
            field=models.IntegerField(unique=True, verbose_name='時給'),
        ),
        migrations.AlterField(
            model_name='work',
            name='Worked_date',
            field=models.DateField(default=datetime.date(2022, 11, 3), verbose_name='勤務日'),
        ),
    ]
