# Generated by Django 4.1.1 on 2022-11-23 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0009_alter_wage_name_alter_work_worked_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yearwage',
            name='number',
        ),
    ]
