# Generated by Django 4.1.1 on 2022-11-03 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0009_alter_wage_name_alter_work_worked_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='Worktime_m',
            field=models.IntegerField(default=0, verbose_name='勤務時間-分'),
        ),
    ]
