# Generated by Django 4.1.1 on 2022-12-26 03:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0010_remove_yearwage_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='Worked_date',
            field=models.DateField(default=datetime.date(2022, 12, 26), verbose_name='勤務日'),
        ),
    ]
