# Generated by Django 4.1.1 on 2022-11-03 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0010_alter_work_worktime_m'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='Worktime_h_2',
            field=models.IntegerField(blank=True, null=True, verbose_name='勤務時間-時間'),
        ),
        migrations.AddField(
            model_name='work',
            name='Worktime_m_2',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='勤務時間-分'),
        ),
        migrations.AddField(
            model_name='work',
            name='wage_2',
            field=models.IntegerField(blank=True, null=True, verbose_name='時給'),
        ),
    ]
