# Generated by Django 4.1.1 on 2022-11-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0011_work_worktime_h_2_work_worktime_m_2_work_wage_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='zangyo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.IntegerField(verbose_name='残業手当')),
            ],
        ),
        migrations.AddField(
            model_name='work',
            name='zangyo',
            field=models.IntegerField(blank=True, null=True, verbose_name='残業時間'),
        ),
    ]
