# Generated by Django 4.1.1 on 2022-11-03 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0012_zangyo_work_zangyo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='zangyo',
        ),
        migrations.AddField(
            model_name='work',
            name='zangyo_h',
            field=models.IntegerField(blank=True, null=True, verbose_name='残業時間（時間）'),
        ),
        migrations.AddField(
            model_name='work',
            name='zangyo_m',
            field=models.IntegerField(blank=True, null=True, verbose_name='残業時間（分）'),
        ),
    ]
