# Generated by Django 4.1.1 on 2022-11-03 15:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0013_remove_work_zangyo_work_zangyo_h_work_zangyo_m'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zangyo',
            old_name='Name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='work',
            name='Worked_date',
            field=models.DateField(default=datetime.date(2022, 11, 4), verbose_name='勤務日'),
        ),
    ]
