# Generated by Django 4.1.1 on 2022-11-14 10:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0014_rename_name_zangyo_name_alter_work_worked_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='total_yukyu',
            name='name',
            field=models.PositiveIntegerField(verbose_name='有給'),
        ),
        migrations.AlterField(
            model_name='wage',
            name='name',
            field=models.PositiveIntegerField(unique=True, verbose_name='時給'),
        ),
        migrations.AlterField(
            model_name='work',
            name='Worked_date',
            field=models.DateField(default=datetime.date(2022, 11, 14), unique=True, verbose_name='勤務日'),
        ),
        migrations.AlterField(
            model_name='work',
            name='Worktime_h',
            field=models.PositiveIntegerField(verbose_name='勤務時間-時間'),
        ),
        migrations.AlterField(
            model_name='work',
            name='Worktime_h_2',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='勤務時間-時間'),
        ),
        migrations.AlterField(
            model_name='work',
            name='Worktime_m',
            field=models.PositiveIntegerField(default=0, verbose_name='勤務時間-分'),
        ),
        migrations.AlterField(
            model_name='work',
            name='Worktime_m_2',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='勤務時間-分'),
        ),
        migrations.AlterField(
            model_name='work',
            name='total_wage',
            field=models.PositiveIntegerField(editable=False, verbose_name='日給'),
        ),
        migrations.AlterField(
            model_name='work',
            name='wage',
            field=models.PositiveIntegerField(verbose_name='時給'),
        ),
        migrations.AlterField(
            model_name='work',
            name='wage_2',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='時給'),
        ),
        migrations.AlterField(
            model_name='work',
            name='yukyu',
            field=models.PositiveIntegerField(verbose_name='有給'),
        ),
        migrations.AlterField(
            model_name='work',
            name='zangyo_h',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='残業時間（時間）'),
        ),
        migrations.AlterField(
            model_name='work',
            name='zangyo_m',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='残業時間（分）'),
        ),
        migrations.AlterField(
            model_name='yearwage',
            name='name',
            field=models.PositiveIntegerField(default=1000000, unique=True, verbose_name='年収'),
        ),
        migrations.AlterField(
            model_name='zangyo',
            name='name',
            field=models.PositiveIntegerField(verbose_name='残業手当'),
        ),
    ]
